name: OceanBlockSeller
version: '${project.version}'
main: ru.fiarr4ik.oceanblockseller.OceanBlockSeller
api-version: '1.16'
depend: [Vault, Essentials]
commands:
  seller:
  balance:
permissions:
  itembuyer.seller:
  itembuyer.selleredit: