name: OceanBlockSeller
version: '${project.version}'
main: ru.fiarr4ik.oceanblockseller.OceanBlockSeller
api-version: '1.16'
depend: [Vault, Essentials]
commands:
  seller:
  balance:
permissions:
  itembuyer.seller:
    description: Позволяет пользователю использовать команду продавца
    default: true
  itembuyer.selleredit:
    description: Позволяет пользователю управлять торгами продавца
    default: op